# Generated by Django 2.2.3 on 2019-07-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190729_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTag',
        ),
    ]
