# Generated by Django 2.2.3 on 2019-07-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生年月'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_grade',
            field=models.CharField(default='一年级', max_length=50, verbose_name='所在年级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_signature',
            field=models.CharField(default=' ', max_length=50, verbose_name='个性签名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(default='学校', max_length=50, verbose_name='所在学校'),
        ),
    ]
