# Generated by Django 2.0.2 on 2019-07-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citydict',
            options={'verbose_name_plural': '城市'},
        ),
    ]
